=== alexayin/XML/xml-schema/church.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://users.utu.fi/yinwei/church"
xmlns="http://users.utu.fi/yinwei/church"
elementFormDefault="qualified">


<xs:annotation>

	<xs:documentation>

		This document contains the structure of Chinese church in Helsinki.

	</xs:documentation>

</xs:annotation>


<xs:element name="church" type="churchType"/>


<xs:complexType name="churchType">
	<xs:sequence>

		<xs:element name="pastor" type="personInfo"/>

		<xs:element name="deacon" type="personInfo"/>

		<xs:element name="believer" type="personInfo" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>

	<xs:attribute name="location" type="xs:string"/>

</xs:complexType>

<xs:complexType name="personInfo">
	<xs:sequence>
		<xs:element name="lastname" type="xs:string"/>
		<xs:element name="firstname" type="xs:string"/>
		<xs:element name="address" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== alexayin/XML/xml-schema/church.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Thu Jul 21 17:29:33 EEST 2011 -->


<church

xmlns="http://users.utu.fi/yinwei/church"

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

xsi:schemaLocation="http://users.utu.fi/yinwei/church church.xsd">


	<pastor>

		<lastname>Huang</lastname>

		<firstname>Paulos</firstname>

		<address>Helsinki</address>

	</pastor>

	

	<deacon>

		<lastname>Xi</lastname>

		<firstname>Shunrong</firstname>

		<address>Espoo</address>

	</deacon>

	

	<believer>

		<lastname>Yin</lastname>

		<firstname>Alexander</firstname>

		<address>Nummela</address>

	</believer>

	

	<believer>

		<lastname>Yin</lastname>

		<firstname>Jasmine</firstname>

		<address>Nummela</address>

	</believer>

	

	<believer>

		<lastname>Yin</lastname>

		<firstname>Jeremy</firstname>

		<address>Nummela</address>

	</believer>


</church>
